//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesWebApp.NoteService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoteService.NoteServiceSoap")]
    public interface NoteServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FillData(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FillData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FillDataAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertNote(string username, string title, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNote", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertNoteAsync(string username, string title, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateNote(string title, string text, string NoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNote", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateNoteAsync(string title, string text, string NoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteNote(string NoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteNote", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteNoteAsync(string NoteID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoteServiceSoapChannel : NotesWebApp.NoteService.NoteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoteServiceSoapClient : System.ServiceModel.ClientBase<NotesWebApp.NoteService.NoteServiceSoap>, NotesWebApp.NoteService.NoteServiceSoap {
        
        public NoteServiceSoapClient() {
        }
        
        public NoteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FillData(string username) {
            return base.Channel.FillData(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FillDataAsync(string username) {
            return base.Channel.FillDataAsync(username);
        }
        
        public bool InsertNote(string username, string title, string text) {
            return base.Channel.InsertNote(username, title, text);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNoteAsync(string username, string title, string text) {
            return base.Channel.InsertNoteAsync(username, title, text);
        }
        
        public bool UpdateNote(string title, string text, string NoteID) {
            return base.Channel.UpdateNote(title, text, NoteID);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateNoteAsync(string title, string text, string NoteID) {
            return base.Channel.UpdateNoteAsync(title, text, NoteID);
        }
        
        public bool DeleteNote(string NoteID) {
            return base.Channel.DeleteNote(NoteID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteNoteAsync(string NoteID) {
            return base.Channel.DeleteNoteAsync(NoteID);
        }
    }
}
